version: '2'
services:
  proshop:
    links:
      - "db"
    image: proshop
    # expose:
    #   - 5000
    ports:
      - 5000:5000
  db:
    image: mongo
    # expose:
    #   - 27017
    ports:
      - 27017:27017
    command: yarn data:import
